### ISSUE TITLE
Incompat with TechReborn?

### ISSUE THREAD

**Issue by kaliflowerx3** [Sunconure11/alaskanativecraft#2]
Versions: alaskanativecraft 1.4.6, reborncore 5.2.0, techreborn 5.2.0

When a player tries to connect this error is thrown and the server times out:

```
[20:38:11] [Netty Server IO #2/ERROR]: Failed to ser/de techreborn:rolling_machine/rail
reborncore.common.crafting.serde.RecipeSerdeException: Failed to ser/de techreborn:rolling_machine/rail
	at reborncore.common.crafting.RebornRecipeType.toJson(RebornRecipeType.java:65) ~[RebornCore-5.2.0.jar:?]
	at reborncore.common.crafting.RebornRecipeType.write(RebornRecipeType.java:79) ~[RebornCore-5.2.0.jar:?]
	at reborncore.common.crafting.RebornRecipeType.method_8124(RebornRecipeType.java:40) ~[RebornCore-5.2.0.jar:?]
	at net.minecraft.class_2788.method_17816(class_2788.java:52) ~[server-intermediary.jar:?]
	at net.minecraft.class_2540.method_34062(class_2540.java:131) ~[server-intermediary.jar:?]
	at net.minecraft.class_2788.method_11052(class_2788.java:27) ~[server-intermediary.jar:?]
	at net.minecraft.class_2545.method_10838(class_2545.java:45) ~[server-intermediary.jar:?]
	at net.minecraft.class_2545.encode(class_2545.java:14) ~[server-intermediary.jar:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808) ~[netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-all-4.1.68.Final.jar:?]
	at net.minecraft.class_2535.method_36942(class_2535.java:214) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_10761(class_2535.java:206) ~[server-intermediary.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [netty-all-4.1.68.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [netty-all-4.1.68.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-all-4.1.68.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.68.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.UnsupportedOperationException: Cannot write class com.github.platymemo.alaskanativecraft.recipe.AlaskaRecipes$AlaskaSticksEntry
	at reborncore.common.crafting.ShapedRecipeHelper.rewriteForNetworkSync(ShapedRecipeHelper.java:69) ~[RebornCore-5.2.0.jar:?]
	at techreborn.api.recipe.recipes.serde.RollingMachineRecipeSerde.collectJsonData(RollingMachineRecipeSerde.java:29) ~[TechReborn-5.2.0.jar:?]
	at techreborn.api.recipe.recipes.serde.RollingMachineRecipeSerde.collectJsonData(RollingMachineRecipeSerde.java:19) ~[TechReborn-5.2.0.jar:?]
	at reborncore.common.crafting.serde.RebornRecipeSerde.toJson(RebornRecipeSerde.java:60) ~[RebornCore-5.2.0.jar:?]
	at reborncore.common.crafting.RebornRecipeType.toJson(RebornRecipeType.java:63) ~[RebornCore-5.2.0.jar:?]
	... 23 more
[20:38:12] [Netty Server IO #2/ERROR]: Error receiving packet 102
reborncore.common.crafting.serde.RecipeSerdeException: Failed to ser/de techreborn:rolling_machine/rail
	at reborncore.common.crafting.RebornRecipeType.toJson(RebornRecipeType.java:65) ~[RebornCore-5.2.0.jar:?]
	at reborncore.common.crafting.RebornRecipeType.write(RebornRecipeType.java:79) ~[RebornCore-5.2.0.jar:?]
	at reborncore.common.crafting.RebornRecipeType.method_8124(RebornRecipeType.java:40) ~[RebornCore-5.2.0.jar:?]
	at net.minecraft.class_2788.method_17816(class_2788.java:52) ~[server-intermediary.jar:?]
	at net.minecraft.class_2540.method_34062(class_2540.java:131) ~[server-intermediary.jar:?]
	at net.minecraft.class_2788.method_11052(class_2788.java:27) ~[server-intermediary.jar:?]
	at net.minecraft.class_2545.method_10838(class_2545.java:45) ~[server-intermediary.jar:?]
	at net.minecraft.class_2545.encode(class_2545.java:14) ~[server-intermediary.jar:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808) ~[netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-all-4.1.68.Final.jar:?]
	at net.minecraft.class_2535.method_36942(class_2535.java:214) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_10761(class_2535.java:206) ~[server-intermediary.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [netty-all-4.1.68.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) [netty-all-4.1.68.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [netty-all-4.1.68.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-all-4.1.68.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.68.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.UnsupportedOperationException: Cannot write class com.github.platymemo.alaskanativecraft.recipe.AlaskaRecipes$AlaskaSticksEntry
	at reborncore.common.crafting.ShapedRecipeHelper.rewriteForNetworkSync(ShapedRecipeHelper.java:69) ~[RebornCore-5.2.0.jar:?]
	at techreborn.api.recipe.recipes.serde.RollingMachineRecipeSerde.collectJsonData(RollingMachineRecipeSerde.java:29) ~[TechReborn-5.2.0.jar:?]
	at techreborn.api.recipe.recipes.serde.RollingMachineRecipeSerde.collectJsonData(RollingMachineRecipeSerde.java:19) ~[TechReborn-5.2.0.jar:?]
	at reborncore.common.crafting.serde.RebornRecipeSerde.toJson(RebornRecipeSerde.java:60) ~[RebornCore-5.2.0.jar:?]
	at reborncore.common.crafting.RebornRecipeType.toJson(RebornRecipeType.java:63) ~[RebornCore-5.2.0.jar:?]
	... 23 more
[20:38:12] [Netty Server IO #2/INFO]: [STDOUT]: REI: Server failed to synchronize recipe data with the client! Please check the server console log for errors, this breaks REI and vanilla recipe books!
```

**Comment by Sunconure11** [comment]
I'll see if I can take a look at this sometime after the 8th. The mod does something weird to make certain items count as sticks. However, I have not played with Tech Reborn at all, so you might want to also raise them an issue too, simply because I'm not familiar with their mod.
